{
 "title": "RenogyView",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "aggregation_interval", "label": "Granularity", "query": "1m,5m,30m,1h,4h,12h,24h" }
  ]
 },
 "panels": [
  {
   "title": "Solar - Holding Load and/or Charging Battery?",
   "type": "state-timeline",
   "description": "Is solar production overcoming consumption? ",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"power_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> aggregateWindow(every: ${aggregation_interval}, fn: mean, createEmpty: false)\n  |> filter(fn: (r) => \n      not (\n          (r.device == \"Inverter\" and r._field == \"AmpsMPPT\") or \n          (r.device == \"Inverter\" and r._field == \"WattsMain\")\n      )  // Exclude specific rows\n  )\n  |> filter(fn: (r) => r.device == \"Solar\" or r.device == \"Inverter\" or r.device == \"Main\")\n  |> filter(fn: (r) => r._field == \"AmpsMPPT\" or r._field == \"WattsMain\" or r._field == \"WattsInv\")\n  |> group()  // Remove any residual grouping to unify the data\n  |> map(fn: (r) => ({\n      r with \n      _field: if r._field == \"WattsMain\" then \"AmpsMain\" else if r._field == \"WattsInv\" then \"AmpsInv\" else r._field\n  }))\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")  // Align fields as columns\n  |> map(fn: (r) => ({\n      r with \n      AmpsLoad: ((r.AmpsInv + r.AmpsMPPT) - r.AmpsMain),  // Calculate AmpsLoad\n  }))\n    |> map(fn: (r) => ({\n      r with \n      Charging: r.AmpsMPPT >= r.AmpsLoad and r.AmpsMain >= 0  and r.AmpsInv <= 1,\n      Holding: r.AmpsMPPT >= r.AmpsLoad\n  }))\n  |> keep(columns: [\"_time\", \"Holding\",\"Charging\"])\n  |> sort(columns: [\"_time\"], desc: false)  // Ensure ascending time order\n  |> yield(name: \"charge_status\")"
    }
   ]
  },
  {
   "title": "Solar Power (Max 1200W)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"power_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> aggregateWindow(every: ${aggregation_interval}, fn: mean, createEmpty: false)\n  |> filter(fn: (r) => r.device == \"Solar\")\n  |> filter(fn: (r) => r._field == \"WattsMPPT\" or r._field == \"WattsSolar\")\n  |> group(columns: [\"_field\", \"device\"])  // Group by field and device for better series separation\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])  // Keep only relevant fields\n  |> sort(columns: [\"_time\"], desc: false)\n  |> yield(name: \"chargerwatts\")"
    }
   ]
  },
  {
   "title": "State of Charge",
   "type": "gauge",
   "description": "State of Charge based on Voltage",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"power_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> aggregateWindow(every: ${aggregation_interval}, fn: mean, createEmpty: false)\n  |> filter(fn: (r) => r._field == \"VoltsMain\" and r.device == \"Main\")\n  |> map(fn: (r) => ({\n      r with \n      SoC: if r._value >= 13.5 then 100.0 else\n           if r._value >= 13.35 then 99.0 else\n           if r._value >= 13.3 then 90.0 else\n           if r._value >= 13.25 then 80.0 else\n           if r._value >= 13.2 then 70.0 else\n           if r._value >= 13.16 then 60.0 else\n           if r._value >= 13.13 then 50.0 else\n           if r._value >= 13.1 then 40.0 else\n           if r._value >= 13.0 then 30.0 else\n           if r._value >= 12.9 then 20.0 else\n           if r._value >= 12.8 then 10.0 else\n           if r._value >= 12.3 then 5.0 else\n           if r._value >= 11.7 then 7.5 else\n           if r._value >= 11.0 then 2.0 else\n           if r._value >= 10.8 then 1.0 else\n           0.0  // Below Low Voltage Disconnect\n  }))\n  |> keep(columns: [\"_time\", \"SoC\"])  // Keep only time and calculated SoC\n  |> yield(name: \"state_of_charge\")"
    }
   ]
  },
  {
   "title": " Run Time (0-7 days)",
   "type": "stat",
   "description": "State of Charge based on Voltage",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "// State of Charge (SoC) Stream\nsoc_stream = from(bucket: \"power_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> aggregateWindow(every: ${aggregation_interval}, fn: mean, createEmpty: false)\n  |> filter(fn: (r) => r._field == \"VoltsMain\" and r.device == \"Main\")\n  |> map(fn: (r) => ({\n      r with \n      SoC: if r._value >= 13.5 then 100.0 else\n           if r._value >= 13.35 then 99.0 else\n           if r._value >= 13.3 then 90.0 else\n           if r._value >= 13.25 then 80.0 else\n           if r._value >= 13.2 then 70.0 else\n           if r._value >= 13.16 then 60.0 else\n           if r._value >= 13.13 then 50.0 else\n           if r._value >= 13.1 then 40.0 else\n           if r._value >= 13.0 then 30.0 else\n           if r._value >= 12.9 then 20.0 else\n           if r._value >= 12.8 then 10.0 else\n           if r._value >= 12.3 then 5.0 else\n           if r._value >= 11.7 then 7.5 else\n           if r._value >= 11.0 then 2.0 else\n           if r._value >= 10.8 then 1.0 else\n           0.0\n  }))\n  |> keep(columns: [\"_time\", \"SoC\"])\n\n// Amperage Main Stream\nampsLoad_stream = from(bucket: \"power_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> aggregateWindow(every: ${aggregation_interval}, fn: mean, createEmpty: false)\n  |> filter(fn: (r) => \n      not (\n          (r.device == \"Inverter\" and r._field == \"AmpsMPPT\") or \n          (r.device == \"Inverter\" and r._field == \"WattsMain\")\n      )  // Exclude specific rows\n  )\n  |> filter(fn: (r) => r.device == \"Solar\" or r.device == \"Inverter\" or r.device == \"Main\")\n  |> filter(fn: (r) => r._field == \"AmpsMPPT\" or r._field == \"WattsMain\" or r._field == \"WattsInv\")\n  |> map(fn: (r) => ({\n      r with \n      _field: if r._field == \"WattsMain\" then \"AmpsMain\" else if r._field == \"WattsInv\" then \"AmpsInv\" else r._field\n  }))\n  |> group()  // Remove any residual grouping to unify the data\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")  // Align fields into columns\n  |> map(fn: (r) => ({\n      r with \n      AmpsLoad: if exists r.AmpsInv and exists r.AmpsMPPT and exists r.AmpsMain then (r.AmpsInv + r.AmpsMPPT) - r.AmpsMain else float(v: 0.0)\n  }))\n  |> keep(columns: [\"_time\", \"AmpsLoad\"])  // Keep only relevant columns\n\n// Combine SoC and Runtime Calculation\njoin(tables: {soc: soc_stream, amps: ampsLoad_stream}, on: [\"_time\"])\n  |> map(fn: (r) => ({\n      r with \n      RuntimeHours: if r.AmpsLoad > 0.0 then ((r.SoC/100.0) * 800.0) / r.AmpsLoad else float(v: 0.0),\n      RuntimeDays: if r.AmpsLoad > 0.0 then (((r.SoC/100.0) * 800.0) / r.AmpsLoad) / 24.0 else float(v: 0.0)\n  }))\n  |> keep(columns: [\"_time\", \"RuntimeHours\"])  // Keep only relevant fields\n  |> sort(columns: [\"_time\"], desc: false)\n  |> yield(name: \"soc_runtime\")"
    }
   ]
  },
  {
   "title": "Solar Generation",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"power_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> aggregateWindow(every: ${aggregation_interval}, fn: mean, createEmpty: false)\n  |> filter(fn: (r) => r.device == \"Solar\")\n  |> filter(fn: (r) => r._field == \"AmpsSolar\" or r._field == \"VoltsSolar\" or r._field == \"WattsSolar\")\n  |> group(columns: [\"_field\", \"device\"])  // Group by field and device for better series separation\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])  // Keep only relevant fields\n  |> sort(columns: [\"_time\"], desc: false)\n  |> yield(name: \"voltage_data\")"
    }
   ]
  },
  {
   "title": "Power ",
   "type": "timeseries",
   "description": "Production (MPPT and Charger) less what's feeding the battery",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"power_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> aggregateWindow(every: ${aggregation_interval}, fn: mean, createEmpty: false)\n  |> filter(fn: (r) => \n      not (\n          (r.device == \"Inverter\" and r._field == \"AmpsMPPT\") or \n          (r.device == \"Inverter\" and r._field == \"WattsMain\")\n      )  // Exclude specific rows\n  )\n  |> filter(fn: (r) => r.device == \"Solar\" or r.device == \"Inverter\" or r.device == \"Main\")\n  |> filter(fn: (r) => r._field == \"AmpsMPPT\" or r._field == \"VoltsMPPT\" or r._field == \"WattsMain\" or r._field == \"WattsInv\" or r._field == \"VoltsMain\" or r._field == \"VoltsInv\")\n\n  |> map(fn: (r) => ({\n      r with \n      _field: if r._field == \"WattsMain\" then \"AmpsMain\" else if r._field == \"WattsInv\" then \"AmpsInv\" else r._field\n  }))\n  |> group()  // Remove any residual grouping to unify the data\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")  // Align fields into columns\n  |> map(fn: (r) => ({\n      r with \n      WattsMPPT: if exists r.AmpsMPPT and exists r.VoltsMPPT then (r.AmpsMPPT * r.VoltsMPPT)  else float(v: 0.0),\n      WattsMain: if exists r.AmpsMain and exists r.VoltsMain then (r.AmpsMain * r.VoltsMain)  else float(v: 0.0),\n      WattsInv: if exists r.AmpsInv and exists r.VoltsInv then (r.AmpsInv * r.VoltsInv)  else float(v: 0.0)\n  }))\n  |> keep(columns: [\"_time\", \"WattsMPPT\", \"WattsMain\", \"WattsInv\"])  // Keep only relevant columns\n  |> sort(columns: [\"_time\"], desc: false)\n  |> yield(name: \"wattage_load\")"
    }
   ]
  },
  {
   "title": "Power ",
   "type": "stat",
   "description": "Production (MPPT and Charger) less what's feeding the battery",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"power_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> aggregateWindow(every: ${aggregation_interval}, fn: mean, createEmpty: false)\n  |> filter(fn: (r) => \n      not (\n          (r.device == \"Inverter\" and r._field == \"AmpsMPPT\") or \n          (r.device == \"Inverter\" and r._field == \"WattsMain\")\n      )  // Exclude specific rows\n  )\n  |> filter(fn: (r) => r.device == \"Solar\" or r.device == \"Inverter\" or r.device == \"Main\")\n  |> filter(fn: (r) => r._field == \"AmpsMPPT\" or r._field == \"VoltsMPPT\" or r._field == \"WattsMain\" or r._field == \"WattsInv\" or r._field == \"VoltsMain\" or r._field == \"VoltsInv\")\n  |> map(fn: (r) => ({\n      r with \n      _field: if r._field == \"WattsMain\" then \"AmpsMain\" else if r._field == \"WattsInv\" then \"AmpsInv\" else r._field\n  }))\n  |> group()  // Remove any residual grouping to unify the data\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")  // Align fields into columns\n  |> map(fn: (r) => ({\n      r with \n      WattsMain: if exists r.AmpsMain and exists r.VoltsMain then (r.AmpsMain * r.VoltsMain)  else float(v: 0.0),\n      WattsInv: if exists r.AmpsInv and exists r.VoltsInv then (r.AmpsInv * r.VoltsInv)  else float(v: 0.0),\n      WattsMPPT: if exists r.AmpsMPPT and exists r.VoltsMPPT then (r.AmpsMPPT * r.VoltsMPPT)  else float(v: 0.0)\n  }))\n|> keep(columns: [\"WattsMain\", \"WattsInv\", \"WattsMPPT\", \"_time\"])  // Note order explicitly here\n|> sort(columns: [\"_time\"], desc: false)  // Ensure proper time ordering\n|> yield(name: \"wattage_load\")"
    }
   ]
  },
  {
   "title": "Load Power ",
   "type": "stat",
   "description": "Production (MPPT and Charger) less what's feeding the battery",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"power_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> aggregateWindow(every: ${aggregation_interval}, fn: mean, createEmpty: false)\n  |> filter(fn: (r) => \n      not (\n          (r.device == \"Inverter\" and r._field == \"AmpsMPPT\") or \n          (r.device == \"Inverter\" and r._field == \"WattsMain\")\n      )  // Exclude specific rows\n  )\n  |> filter(fn: (r) => r.device == \"Solar\" or r.device == \"Inverter\" or r.device == \"Main\")\n  |> filter(fn: (r) => r._field == \"AmpsMPPT\" or r._field == \"WattsMain\" or r._field == \"WattsInv\" or r._field == \"VoltsMain\")\n  |> map(fn: (r) => ({\n      r with \n      _field: if r._field == \"WattsMain\" then \"AmpsMain\" else if r._field == \"WattsInv\" then \"AmpsInv\" else r._field\n  }))\n  |> group()  // Remove any residual grouping to unify the data\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")  // Align fields into columns\n  |> map(fn: (r) => ({\n      r with \n      WattsLoad: if exists r.AmpsInv and exists r.AmpsMPPT and exists r.AmpsMain then ((r.AmpsInv + r.AmpsMPPT) - r.AmpsMain)*r.VoltsMain else float(v: 0.0)\n  }))\n  |> keep(columns: [\"_time\", \"WattsLoad\"])  // Keep only relevant columns\n  |> sort(columns: [\"_time\"], desc: false)\n  |> yield(name: \"wattage_load\")"
    }
   ]
  },
  {
   "title": "Amperage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"power_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> aggregateWindow(every: ${aggregation_interval}, fn: mean, createEmpty: false)\n  |> filter(fn: (r) => r.device == \"Solar\" or r.device == \"Inverter\" or r.device == \"Main\")\n  |> filter(fn: (r) => r._field == \"AmpsMPPT\" or r._field == \"WattsMain\" or r._field == \"WattsInv\")\n  |> map(fn: (r) => ({\n      r with \n      _field: if r._field == \"WattsMain\" then \"AmpsMain\" else if r._field == \"WattsInv\" then \"AmpsInv\" else r._field\n  }))\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])  // Keep relevant fields\n  |> sort(columns: [\"_time\"], desc: false)\n  |> yield(name: \"amperage_data\")"
    }
   ]
  },
  {
   "title": "Amperage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"power_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> aggregateWindow(every: ${aggregation_interval}, fn: mean, createEmpty: false)\n  |> filter(fn: (r) => r.device == \"Solar\" or r.device == \"Inverter\" or r.device == \"Main\")\n  |> filter(fn: (r) => r._field == \"AmpsMPPT\" or r._field == \"WattsMain\" or r._field == \"WattsInv\")\n  |> map(fn: (r) => ({\n      r with \n      _field: if r._field == \"WattsMain\" then \"AmpsMain\" else if r._field == \"WattsInv\" then \"AmpsInv\" else r._field\n  }))\n  |> group()  // Remove any residual grouping to unify the data\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")  // Align fields as columns\n    |> map(fn: (r) => ({\n    r with \n    AmpsMain: r.AmpsMain,\n    AmpsInv: r.AmpsInv,\n    AmpsMPPT: r.AmpsMPPT\n}))\n  |> keep(columns: [\"AmpsMain\", \"AmpsInv\", \"AmpsMPPT\", \"_time\", ])  // Keep only relevant columns\n  |> sort(columns: [\"_time\"], desc: false)  // Ensure ascending time order\n  |> yield(name: \"amperage_data\")"
    }
   ]
  },
  {
   "title": "Load Amps ",
   "type": "stat",
   "description": "Production (MPPT and Charger) less what's feeding the battery",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"power_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> aggregateWindow(every: ${aggregation_interval}, fn: mean, createEmpty: false)\n  |> filter(fn: (r) => \n      not (\n          (r.device == \"Inverter\" and r._field == \"AmpsMPPT\") or \n          (r.device == \"Inverter\" and r._field == \"WattsMain\")\n      )  // Exclude specific rows\n  )\n  |> filter(fn: (r) => r.device == \"Solar\" or r.device == \"Inverter\" or r.device == \"Main\")\n  |> filter(fn: (r) => r._field == \"AmpsMPPT\" or r._field == \"WattsMain\" or r._field == \"WattsInv\")\n  |> map(fn: (r) => ({\n      r with \n      _field: if r._field == \"WattsMain\" then \"AmpsMain\" else if r._field == \"WattsInv\" then \"AmpsInv\" else r._field\n  }))\n  |> group()  // Remove any residual grouping to unify the data\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")  // Align fields into columns\n  |> map(fn: (r) => ({\n      r with \n      AmpsLoad: if exists r.AmpsInv and exists r.AmpsMPPT and exists r.AmpsMain then (r.AmpsInv + r.AmpsMPPT) - r.AmpsMain else float(v: 0.0)\n  }))\n  |> keep(columns: [\"_time\", \"AmpsLoad\"])  // Keep only relevant columns\n  |> sort(columns: [\"_time\"], desc: false)\n  |> yield(name: \"amperage_load\")"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"power_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> aggregateWindow(every: ${aggregation_interval}, fn: mean, createEmpty: false)\n  |> filter(fn: (r) => r.device == \"Solar\" or r.device == \"Inverter\" or r.device == \"Main\")\n  |> filter(fn: (r) => r._field == \"VoltsMPPT\" or r._field == \"VoltsInv\" or r._field == \"VoltsMain\")\n  |> group(columns: [\"_field\", \"device\"])  // Group by field and device for better series separation\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])  // Keep only relevant fields\n  |> sort(columns: [\"_time\"], desc: false)\n  |> yield(name: \"voltage_data\")"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"power_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> aggregateWindow(every: ${aggregation_interval}, fn: mean, createEmpty: false)\n  |> filter(fn: (r) => r.device == \"Solar\" or r.device == \"Inverter\" or r.device == \"Main\")\n  |> filter(fn: (r) => r._field == \"VoltsMPPT\" or r._field == \"VoltsInv\" or r._field == \"VoltsMain\")\n  |> group(columns: [\"_field\", \"device\"])  // Group by field and device for better series separation\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])  // Keep only relevant fields\n  |> sort(columns: [\"_time\"], desc: false)\n  |> yield(name: \"voltage_data\")"
    }
   ]
  },
  {
   "title": "Battery Temp",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"power_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> aggregateWindow(every: ${aggregation_interval}, fn: mean, createEmpty: false)\n  |> filter(fn: (r) => r.device == \"Solar\")\n  |> filter(fn: (r) => r._field == \"BatteryTemp\")  // Focus on temperature\n  |> sort(columns: [\"_time\"], desc: false)\n  |> yield(name: \"ConvertedTemperature\")"
    }
   ]
  }
 ]
}